spring:
  profiles:
    active: test
  main:
      allow-bean-definition-overriding: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: filesystem:src/migration
    baseline-version: 1
    url: "jdbc:mysql://localhost:3366/samplestore"
    user: root
    password: 12345
    clean-disabled: false
    validate-on-migrate: true

board:
  domain:
    datasource:
      poolName: custom-domain-cp
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: "jdbc:mysql://localhost:3366/samplestore?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Seoul"
      username: root
      password: 12345
      auto-commit: false
      sqlScriptEncoding: UTF-8
      connectionTimeout: 60000
      maxLifetime: 60000
      maximumPoolSize: 5

logging:
  level:
    com.example.border: DEBUG
    org.springframework.jdbc: TRACE
